### ISSUE TITLE
there is too many build errors when i use fcml

### ISSUE THREAD

**Issue by stonedreamforest** [swojtasiak/fcml-lib#146]
![image](https://user-images.githubusercontent.com/16742566/60757750-21173c00-a041-11e9-81eb-aa1cc1cdd0d0.png)

```.CPP
#include <fcml_intel_mnemonics.hpp>

#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>


void test_fcml::fcml_main(int argc , char **argv) {
// Notice that it is an array of strings.
	const fcml_string instructions[] = {
		"start:      mov ebx, 1" ,
		"loop_big:   inc ebx" ,
		"            cmp ebx, 10" ,
		"            je  finish" ,
		"loop_small: mov eax, 1" ,
		"increment:  inc eax" ,
		"            cmp eax, 10" ,
		"            je  finish_small" ,
		"            jmp increment" ,
		"finish_small:" ,
		"            jmp loop_big" ,
		"finish:     ret" ,
		NULL
	};
	using namespace fcml;
	using namespace fcml::intel;
	fcml::IntelDialect dialect;
	//ParserContext ctx(0x401000);
	//Parser parser(dialect);
	//ParserResult result;
	//parser.parse(ctx , _FT("mov eax, dword [0x0401000]") , result);
	//const Instruction &instruction = result.getInstruction();
}

```

any sample step to add header file?  just like only add  `fcml_header.hpp`

**Comment by stonedreamforest** [comment]
build hsdis：
![image](https://user-images.githubusercontent.com/16742566/60758671-81f84180-a04c-11e9-8fae-489e76b6045b.png)

**Comment by stonedreamforest** [comment]
I think this problem is caused by _`identifier "fcml_cstring" is undefined `_

**Comment by stonedreamforest** [comment]
I had solved this.

**Comment by swojtasiak** [comment]
I'm glad you managed to fix the problem. Using Windows builds on master may be a bit tricky because they are not up to date. I'm going to adjust them when AVX512 development is finished. I just develop under GNU/Linux and do not have time to check these builds after every change.
