### ISSUE TITLE
Got wrong result when disassembling an instruction

### ISSUE THREAD

**Issue by jr-shen** [swojtasiak/fcml-lib#313]
I used FCML library to disassemble a machine instruction 0x488d148500000000，whose correct disassembly result is
`lea 0x00(, %rax, 4), %rdx`

However, when I use FCML-Disassembler, FCML generates result like this: `lea 0x0000000000000000,%rdx`
```
$ ./fcml_disasm -gas -m64 488d148500000000
Basic information:
 Disassembled instruction: lea 0x0000000000000000,%rdx
```

I also check that FCML-Assembler will produce right result
```
$ ./fcml_asm -gas -m64 "lea 0(,%rax,4), %rdx" 
Number of the assembled instructions: 1
Instruction: 1
 Code: 488d148500000000
 Code length: 8
Best instruction chosen by the assembler: 1
```

I found that the BUG locates in `fcml_modrm_decoder.c`，in function `decode_sib`，below the comment `/* Base register and displacement.*/`。When `f_mod == 0 && FCML_MODRM_SIB_BASE(sib) == 5`，the address_from will be set to FCML_AF_OFFSET directly. However, although `lea 0x00(, %rax, 4), %rdx` satisfies f_mod == 0 and it does not have base register(so that FCML_MODRM_SIB_BASE(sib) == 5), it still has the index register, and can not be categorized to FCML_AF_OFFSET form. So I modified the source code to
```
/* Base register and displacement.*/
    if (f_mod == 0 && FCML_MODRM_SIB_BASE(sib) == 5) {

        address->address_form = FCML_MODRM_SIB_INDEX(sib) == 4 ? FCML_AF_OFFSET : FCML_AF_COMBINED; /* ------------------ changed ------------------- */

        /* In this case base register doesn't exist.*/
        error = decode_displacement(context,
                stream, &(effective_address->displacement),
                &(modrm_details->displacement), &(address->offset), FCML_DS_32,
                effective_address_size, 0);

    }
```

And this BUG seems to be solved, and all unit tests pass.

**Comment by swojtasiak** [comment]
Thanks for the investigation and for the fix. I'll try to apply it tomorrow.
