### ISSUE TITLE
Failed to generate segment override prefix

### ISSUE THREAD

**Issue by jr-shen** [swojtasiak/fcml-lib#314]
I used fcml-asm to assemble such code:
```
mov %rax, %gs:0x44
```
However, it generated wrong instruction: 6748a344000000, whose disassembly result is `mov %rax, 0x44`. The segment register %gs is lost. In the wrong assembly result, there's no segment override prefix 0x65 which represents "%gs" at the beginning of the machine code.

There may be some BUGs in function operand_encoder_segment_relative_offset in fcml_encoding.c I guess, because after I added the following code (which comes from operand_encoder_rm function) to operand_encoder_segment_relative_offset, it can generate correct result.

```
const fcml_st_register *base =
        &(args->operand->address.effective_address.base);
const fcml_st_segment_selector *segment_selector =
        &(args->operand->address.segment_selector);
const fcml_st_register *segment_register =
        &(segment_selector->segment_selector);

if (segment_register->type == FCML_REG_SEG) {
    if (!(args->addr_mode_def->instruction_group
          & FCML_AMT_BRANCH)
        && !(base->type == FCML_REG_GPR
             && (base->reg == FCML_REG_BP
                 || base->reg == FCML_REG_SP))) {
        if (segment_register->reg != FCML_REG_DS) {
            args->context->segment_override = *segment_register;
        }
    }
}
```

**Comment by swojtasiak** [comment]
Thanks for the catch. It was exactly the place where the bug was located. Segment override was just ignored in case of segment relative offset addressing.
