### ISSUE TITLE
Got incorrect result when disassembling an AVX2 instruction

### ISSUE THREAD

**Issue by jr-shen** [swojtasiak/fcml-lib#318]
I used FCML library to disassemble a machine instruction `c5fdd7c1`，whose correct disassembly result is
`vpmovmskb %ymm1, %eax`

But FCML disassembler gives `vpmovmskb %ymm0,%rax`, it seems that both the source operand register, and the destination operand register size are incorrect.

I found that in fcml_def.c, the addr_mode_desc of vpmovmskb instruction is 
```
   {FCML_AMT_AVX_SIMD, FCML_NO_DETAILS, F_L0 | F_VEX | F_IGNORE_L | F_66, IS_MODRM | MODE3264 | EOSA64_FORCE | OPCODE_NUM(2) | PRIMARY_OPCODE(1), {0xf, 0xd7, 0x22}, {FCML_OP_MODRM_R_W, FCML_OP_VEX_VVVV_REG(FCML_REG_SIMD, FCML_EOS_XWORD), FCML_NA, FCML_NA, FCML_NA}, FCML_AM_UNKNOWN, FCML_HINT_NO_HINTS},
    {FCML_AMT_AVX2_SIMD, FCML_NO_DETAILS, F_L1 | F_VEX | F_IGNORE_L | F_66, IS_MODRM | MODE3264 | EOSA64_FORCE | OPCODE_NUM(2) | PRIMARY_OPCODE(1), {0xf, 0xd7, 0x22}, {FCML_OP_MODRM_R_W, FCML_OP_VEX_VVVV_REG(FCML_REG_SIMD, FCML_EOS_YWORD), FCML_NA, FCML_NA, FCML_NA}, FCML_AM_UNKNOWN, FCML_HINT_NO_HINTS}
```

It seems that this addr_mode_desc uses VEX.vvvv to specify the source operand register. However, the Intel Architectures Software Developer's Manual said that in VPMOVMSKB instruction, VEX.vvvv is reserved and must be 1111b, and ModRM should be used to encode the source operand. That's the reason for the first problem, I guess.

**Comment by swojtasiak** [comment]
Thanks for reporting the issue, I'll try to take a look at it today or tomorrow :)

**Comment by swojtasiak** [comment]
A great analysis, it was exactly the source of the issue.
