### ISSUE TITLE
Copypasta in the source release tarball

### ISSUE THREAD

**Issue by skitt** [swojtasiak/fcml-lib#339]
https://github.com/swojtasiak/fcml-lib/releases/download/v1.3.0/fcml-1.3.0.tar.xz contains the following in `include/fcml_assembler.h`:

```c
    /** Set to true in order to force assembler to increment IP address by
     * length of the assembled instruction. */
    fcml_bool increment_ip;git push --set-upstream origin changelog_update
```

The repository is fine, I imagine this was a mistake when preparing the tarball for upload.

**Comment by swojtasiak** [comment]
Thanks for reporting. I've just re-uploaded the dist files.
